config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'google_api#redirect', as: 'redirect'
  get '/callback', to: 'google_api#callback', as: 'callback'
  get '/dashboard_events', to: 'google_api#dashboard_events'
  get '/calendars', to: 'google_api#calendars', as: 'calendars'
  get '/timeslots', to: 'google_api#timeslots'
  get '/create_event', to: 'google_api#create_event'
  devise_for :users
  root to: 'pages#home'
  get '/', to: 'pages#homepage'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  resources :users do
    resources :events
  end
  resources :events do
    resources :slots, only: %i[index new create update]
  end
  resources :slots, only: [:destroy]
  delete '/events/:id', to: 'events#destroy'
  patch '/slots/:id', to: 'slots#update_event'
end

app/views/shared/_events.html.erb
<div class=index-container>
  <div class=mymeetings-container>
    <H2>Meetings I have created</H2> <br>
    <ul>
      <% if current_user.events.length != 0 %>
        <% current_user.events.each do |event| %>
          <li>Meeting: <%= event.name %>
              - description: <%= event.description %>
              - duration: <%= event.duration %> min
              - start: <%= event.start_time %>
              - end: <%= event.end_time %>
              - created by: <%= event.user.first_name %>
              - attendees: <% event.user_events.each do |user| %>
              <%= user.user.first_name %>
              <% end %>
              <%= link_to "Edit", edit_user_event_path(current_user, event) %>
              <%= link_to "Delete", event_path(event),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
              <%= link_to "Available slots for this meeting", event_slots_path(event) %></li>
        <% end %>
      <% else %>
        <%= "You haven't created any meeting yet" %>
      <% end %>
    </ul>
    <div class= invitemeeting-container> <br>
      <H2>Meetings I've been invited to</H2>
      <ul>
        <% current_user.user_events.each do |user_event| %>
          <li>Meeting: <%= user_event.event.name %>
            - description: <%= user_event.event.description %>
            - duration: <%= user_event.event.duration %> min
            - start: <%= user_event.event.start_time %>
            - end: <%= user_event.event.end_time %>
            - invited by: <%= user_event.event.user.first_name %></li>
            - attendees: <% user_event.event.user_events.each do |user| %>
              <%= user.user.first_name %>
            <% end %>
            <br>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-basic">
    <footer>
        <div class="social">
         Find our open source code on Github: <a href="https://github.com/Ade2387/Meet-app"><i  class="icon ion-social-github"></i></a>
        </div>
        <p class="copyright">Meet-app.online © 2022</p>
    </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <%# <div class ="navbar-title">
          <% if user_signed_in?  %>
            <%# <h3><%= "Welcome to Meet, #{current_user.first_name}!"</h3> %>
          <%# <% end %>
        <%# </div> %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", "/dashboard", class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<%# <div class="profile-container">
  <div class="top-profile-container">
    <div class="avatar-picture">
      <% if current_user.photo.attached? %>
        <%# <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
      <%# <% else %>
        <%# <%= image_tag "avatar_default.png" %>
      <%# <% end %>
    <%# </div> %>
    <%# <div class="profile-command"> %>
      <%# <div class="profile-text"> %>
      <%# <h4><%= current_user.first_name <%= current_user.last_name</h4>  %>
      <%# <p><%= "My company: #{current_user.company}"</p>  %>
      <%# <p><%= link_to "Dashboard", "/dashboard"</p>  %>
      <%# <p><%= link_to "Settings", "/users/edit"</p>  %>
      <%# <p><%= link_to "Log out", destroy_user_session_path, method: :delete</p> %>
      <%# </div> %>
    <%# </div> %>
  <%# </div> %>
<%# </div>  %>

<aside>
  <div class="navigation" data-controller="sidebar" data-action="click->sidebar#active">
    <div class="avatar-picture">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
      <% else %>
        <%= image_tag "avatar_default.png" %>
      <% end %>
    </div>
    <div class="text">
      <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
      <p><%= "My team: #{current_user.company}" %></p>
    </div>
    <ul>
      <li class="list" data-sidebar-target="list">
        <b></b>
        <b></b>
          <%= link_to "/dashboard" do %>
              <span class="icon">
                <ion-icon name="home-outline"></ion-icon>
              </span>
              <span class="title">Calendar</span>
          <% end %>
      </li>
      <li class="list" data-sidebar-target="list">
        <b></b>
        <b></b>
          <%= link_to "/users/edit" do %>
              <span class="icon">
                <ion-icon name="settings-outline"></ion-icon>
              </span>
              <span class="title">Setting</span>
          <% end %>
      </li>
      <li class="list" data-sidebar-target="list">
        <b></b>
        <b></b>
          <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="icon">
                <ion-icon name="log-out-outline"></ion-icon>
              </span>
              <span class="title">Log out</span>
          <% end %>
      </li>
    </ul>
  </div>
</aside>
<%# <aside class="sidebar">
      <div class="profile-container">
        <div class="top-profile-container">
          <div class="avatar-picture"> %>
            <%# if current_user.photo.attached? %>
              <%#= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
            <%# else %>
              <%#= image_tag "avatar_default.png" %>
            <%# end %>
          <%# </div> <br>
          <div class="profile-command">
            <div class="profile-text"> %>
              <%# <h4><%= current_user.first_name %> <%#= current_user.last_name %></h4>
              <%# <p><%= "My team: #{current_user.company}" %></p>
              <%# <ul class="nav-list">
                <li> %>
                  <%#= link_to "/dashboard" do %>
                    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-button" viewBox="0 0 16 16">
                      <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0h8A1.5 1.5 0 0 1 11 1.5v2A1.5 1.5 0 0 1 9.5 5h-8A1.5 1.5 0 0 1 0 3.5v-2zM1.5 1a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5h-8z"/>
                      <path d="m7.823 2.823-.396-.396A.25.25 0 0 1 7.604 2h.792a.25.25 0 0 1 .177.427l-.396.396a.25.25 0 0 1-.354 0zM0 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8zm1 3v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2H1zm14-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2h14zM2 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                    <span class="links_name">Dashboard</span> %>
                  <%# end %>
                <%# </li>
                <li> %>
                  <%#= link_to "/users/edit" do %>
                    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                      <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                      <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
                    </svg>
                    <span class="links_name">Setting</span> %>
                  <%# end %>
                <%# </li>
                <li> %>
                  <%#= link_to destroy_user_session_path, method: :delete do %>
                    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                      <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                    </svg>
                    <span class="links_name">Log out</span> %>
                  <%# end %>
                <%# </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </aside> %>