config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'google_api#redirect', as: 'redirect'
  get '/callback', to: 'google_api#callback', as: 'callback'
  get '/dashboard_events', to: 'google_api#dashboard_events'
  get '/calendars', to: 'google_api#calendars', as: 'calendars'
  get '/timeslots', to: 'google_api#timeslots'
  get '/create_event', to: 'google_api#create_event'
  devise_for :users
  root to: 'pages#home'
  get '/', to: 'pages#homepage'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  resources :users do
    resources :events
  end
  resources :events do
    resources :slots, only: %i[index new create update]
  end
  resources :slots, only: [:destroy]
  delete '/events/:id', to: 'events#destroy'
  patch '/slots/:id', to: 'slots#update_event'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events
  has_many :slots, dependent: :destroy
  belongs_to :user
  validates :start_time, :end_time, presence: true
  validates :duration, presence: true, numericality: { only_integer: true }

  default_scope -> { order(:start_time) }  # Our meetings will be ordered by their start_time by default

  def time
    "#{start_time.strftime('%I:%M %p')} - #{end_time.strftime('%I:%M %p')}"
  end

  def multi_days?
    (end_time.to_date - start_time.to_date).to_i >= 1
  end
end

app/controllers/events_controller.rb
require 'date'
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @employees = User.where(company: current_user.company).where.not(id: current_user.id)
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @user_ids = params[:event][:users]
    if @event.save
      if @user_ids.nil? == false
        @user_ids.each do |id|
          @user = User.find(id)
          @event.users << @user
        end
      end
      # creating the attendees email array
      emails = [@event.user.email]
      @event.users.each do |attendee|
        emails.push(attendee.email)
      end
      # calling the timeslot method with the required parameters
      # adding the condition if it's multiple days, we want to run it multiple times for each day individualy
      amount_days = @event.end_time.day - @event.start_time.day
      if amount_days != 0
        day_difference = 1
        days = [[@event.start_time, DateTime.new(@event.start_time.year, @event.start_time.month, @event.start_time.day,@event.end_time.hour, @event.end_time.min, 0, '+1')]]

        amount_days.times do
          part1 = DateTime.new(@event.start_time.year, @event.start_time.month, (@event.start_time.day + day_difference),@event.start_time.hour, @event.start_time.min, 0, '+1')
          part2 = DateTime.new(@event.start_time.year, @event.start_time.month, (@event.start_time.day + day_difference),@event.end_time.hour, @event.end_time.min, 0, '+1')
          days.push([part1, part2])
          day_difference += 1
        end
      else
        days = [@event.start_time, @event.end_time]
      end

      all_days_slots = []

      if amount_days != 0
        days.each do |day|
          all_days_slots.push(timeslots(day[0], day[1], emails, @event.duration))
        end
      else
        all_days_slots.push(timeslots(days[0], days[1], emails, @event.duration))
      end

      all_days_slots.each do |dayslots|
        dayslots.each do |dayslot|
          Slot.create(start_time: dayslot[0].strftime("%B-%d-%H:%M"), end_time: dayslot[1].strftime("%B-%d-%H:%M"), event_id: @event.id, status: "pending")
        end
      end

      # slotarray = timeslots(@event.start_time, @event.end_time, emails, @event.duration)
      # # create the timeslots for the event
      # slotarray.each do |slot|
      #   Slot.create(start_time: slot[0].strftime("%B-%d-%H:%M"), end_time: slot[1].strftime("%B-%d-%H:%M"), event_id: @event.id, status: "pending")
      # end
      redirect_to event_slots_path(@event)
    else
      render :new
    end
  end

  def edit
    @employees = User.where(company: current_user.company).where.not(id: current_user.id)
  end

  def update
    # @new_event = Event.new(event_params)
    # @new_event.user = current_user
    # @user_ids = params[:event][:users]
    create
    # if @new_event.create(event_params)
    Event.find(params[:id]).destroy
    # else
    #   render :edit
    # end
  end

  def destroy
    @event.destroy
    redirect_to "/dashboard", notice: "Your meeting was successfully deleted."
  end

  def timeslots(start_time, end_time, attendees, duration)
    call_google_api
    start_time = start_time.to_datetime
    end_time = end_time.to_datetime

    event_lists_attendees = []
    attendees.each do |attendee|
      x = call_list_events(start_time, end_time, attendee)
      event_lists_attendees.push(x)
    end

    test = []

    event_lists_attendees.each do |eventlist|
      test.push(create_array(eventlist, start_time, end_time))
    end

    while test.length > 1
      part = merge_arrays(test[0], test[1])
      set = [0, 1]
      test.delete_if.with_index { |_, i| set.include? i }
      test.insert(0, part)
    end
    test = test[0]

    sorted_test = test.select { |time| time[0].present? }.sort { |time1, time2| time1[0] <=> time2[0] }

    compact_array(sorted_test)

    free_time_test = free_time(sorted_test)
    test_slots = create_timeslots(duration.minutes, free_time_test)

    return test_slots
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:start_time, :end_time, :description, :duration, :name)
  end

  def call_google_api
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    @service = Google::Apis::CalendarV3::CalendarService.new
    @service.authorization = client
  end

  def call_list_events(time_min, time_max, attendee)
    @service.list_events(attendee, time_min: time_min, time_max: time_max, order_by: "starttime", single_events: true)
  end

  def create_array(array, start_time, end_time)

    answer = []

    boundrie1 = DateTime.new(start_time.to_datetime.year, start_time.to_datetime.month, start_time.to_datetime.day, [start_time.to_datetime.hour, 7].max, start_time.to_datetime.hour <= 7 ? 59 : start_time.to_datetime.min, 0, '+1')
    boundrie11 = DateTime.new(start_time.to_datetime.year, start_time.to_datetime.month, start_time.to_datetime.day, [start_time.to_datetime.hour, 8].max, start_time.to_datetime.hour <= 8 ? 0 : start_time.to_datetime.min, 0, '+1')
    boundrie2 = DateTime.new(end_time.to_datetime.year, end_time.to_datetime.month, end_time.to_datetime.day, [end_time.to_datetime.hour, 18].min, end_time.to_datetime.hour >= 18 ? 00 : end_time.to_datetime.min, 0, '+1')
    boundrie22 = DateTime.new(end_time.to_datetime.year, end_time.to_datetime.month, end_time.to_datetime.day, [end_time.to_datetime.hour, 18].min, end_time.to_datetime.hour >= 18 ? 01 : end_time.to_datetime.min, 0, '+1')

    # array.items[0].start.date_time.day
    answer.push([boundrie1, boundrie11])
    array.items.each do |event|
      answer.push([event.start.date_time, event.end.date_time])
    end
    answer.push([boundrie2, boundrie22])

    return answer
  end

  def merge_arrays(array1, array2)
    merged = []
    array1.each do |x|
      merged.push(x)
    end
    array2.each do |x|
      merged.push(x)
    end
    return merged
  end

  def compact_array(sorted_array)
    index = 0
    while index < (sorted_array.length - 1)
      if sorted_array[index][1] >= sorted_array[index + 1][0]
        if sorted_array[index + 1][1] < sorted_array[index][1]
          sorted_array.delete_at(index + 1)
        else
          new_slot = [sorted_array[index][0], sorted_array[index + 1][1]]
          set = [index, index + 1]
          sorted_array.delete_if.with_index { |_, i| set.include? i }
          sorted_array.insert(index, new_slot)
        end
      else
        index += 1
      end
    end
  end

  def free_time(sorted_array)
    free_time = []
    indexx = 0
    while sorted_array.length > (free_time.length + 1)
      new_frame = [sorted_array[indexx][1], sorted_array[indexx + 1][0]]
      free_time.push(new_frame)
      indexx += 1
    end
    return free_time
  end

  def create_timeslots(duration, free_time_array)
    timeslots = []
    free_time_array.each do |interval|
      subinterval = (interval[0] + duration)
      loops = 0
      while (subinterval) <= interval[1]
        if loops != 0
          slot = [subinterval - duration, subinterval]
          timeslots.push(slot)
          subinterval += duration

        else
          slot = [interval[0], subinterval]
          timeslots.push(slot)
          subinterval += duration
          loops += 1
        end
      end
    end
    return timeslots
  end

  def client_options
    {
      client_id: ENV["GOOGLE_CLIENT_ID"],
      client_secret: ENV["GOOGLE_CLIENT_SECRET"],
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: ENV["CALLBACK_URL"]
    }
  end
end

app/views/events/edit.html.erb
<div class="background">
  <div class="dashboard-container">
    <div class="navigation" data-controller="sidebar" data-action="click->sidebar#active">
      <div class="avatar-picture">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
        <% else %>
          <%= image_tag "avatar_default.png" %>
        <% end %>
      </div>
      <div class="text">
        <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
        <p>My team: <%= link_to current_user.company, events_path, class:"team" %></p>
      </div>
      <ul>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
            <%= link_to "/dashboard" do %>
                <span class="icon">
                  <ion-icon name="home-outline"></ion-icon>
                </span>
                <span class="title">Calendar</span>
            <% end %>
        </li>
        <%# <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b> %>
            <%#= link_to "/events" do %>
                <%# <span class="icon">
                  <ion-icon name="time-outline"></ion-icon>
                </span>
                <span class="title">My meetings</span> %>
            <%# end %>
        <%# </li> %>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
            <%= link_to "/users/edit" do %>
                <span class="icon">
                  <ion-icon name="settings-outline"></ion-icon>
                </span>
                <span class="title">Setting</span>
            <% end %>
        </li>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
            <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="icon">
                  <ion-icon name="log-out-outline"></ion-icon>
                </span>
                <span class="title">Log out</span>
            <% end %>
        </li>
      </ul>
    </div>
    <div class='calendar-border'>
      <div class="event-edit-container">
        <div class="col-12 col-sm-4">
              <H1>Edit meeting:</H1>
              <div class="event-container" data-controller="date">
                <%= simple_form_for([current_user, @event]) do |f| %>
                    <div class=new-car-form>
                      <%= f.input :name %>
                      <%= f.input :description %>
                      <%# duration in sec... need to be in minutes %>
                      <%= f.input :duration %>
                      <%= f.input :start_time, as: :string, input_html: { id: "start_date", data: { 'date-target' => 'start' } } %>
                      <%= f.input :end_time, as: :string, input_html: { id: "end_date", data: { 'date-target' => 'end' }} %>
                      <%= f.input :users, collection: @employees, label_method: :first_name, :as => :check_boxes, include_hidden: false %>
                      <%= f.submit "Edit", class: "btn btn-primary" %>
                    </div>
                  <% end %>
              </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="background">
  <div class="dashboard-container">
    <div class="navigation" data-controller="sidebar" data-action="click->sidebar#active">
      <div class="avatar-picture">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
        <% else %>
          <%= image_tag "avatar_default.png" %>
        <% end %>
      </div>
      <div class="text">
        <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
        <p>My team: <%= link_to current_user.company, events_path, class:"team" %></p>
      </div>
      <ul>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to "/dashboard" do %>
            <span class="icon">
              <ion-icon name="home-outline"></ion-icon>
            </span>
            <span class="title">Calendar</span>
          <% end %>
        </li>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to "/users/edit" do %>
            <span class="icon">
              <ion-icon name="settings-outline"></ion-icon>
            </span>
            <span class="title">Setting</span>
          <% end %>
        </li>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="icon">
              <ion-icon name="log-out-outline"></ion-icon>
            </span>
            <span class="title">Log out</span>
          <% end %>
        </li>
      </ul>
    </div>
    <div class='calendar-border'>
      <div class="team-cards-wrapper">
        <div class="team-card">
            <%= image_tag('picture-Arno.jpg') %>
          <div class="name">
            <h1>Arno Debelle</h1>
          </div>
          <p>Founder</p>
          <p class="mail">
            <a href="mailto: debelle.a@gmail.com">debelle.a@gmail.com</a>
          </p>
        </div>
        <div class="team-card">
            <%= image_tag('picture-Oleg.jpg') %>
          <div class="name">
            <h1>Oleg Deru</h1>
          </div>
          <p>Co-founder</p>
          <p class="mail">
            <a href="mailto: olegderu98@gmail.com">olegderu98@gmail.com</a>
          </p>
        </div>
        <div class="team-card">
            <%= image_tag('picture-Seba.jpg') %>
          <div class="name">
            <h1>Sebastien Neyt</h1>
          </div>
          <p>Co-founder</p>
          <p class="mail">
            <a href="mailto: bas_neyt@hotmail.com">bas_neyt@hotmail.com</a>
          </p>
        </div>
        <div class="team-card">
            <%= image_tag('picture-Anis.jpg') %>
          <div class="name">
            <h1>Anis Samimi</h1>
          </div>
          <p>Co-founder</p>
          <p class="mail">
            <a href="mailto: anis_samimi@hotmail.com">anis_samimi@hotmail.com</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="background">
  <div class="dashboard-container">
    <div class="navigation" data-controller="sidebar" data-action="click->sidebar#active">
      <div class="avatar-picture">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
        <% else %>
          <%= image_tag "avatar_default.png" %>
        <% end %>
      </div>
      <div class="text">
        <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
        <p>My team: <%= link_to current_user.company, events_path, class:"team" %></p>
      </div>
      <ul>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to "/dashboard" do %>
            <span class="icon">
              <ion-icon name="home-outline"></ion-icon>
            </span>
            <span class="title">Calendar</span>
          <% end %>
        </li>
        <%# <li class="list" data-sidebar-target="list">
              <b></b>
              <b></b> %>
        <%#= link_to "/events" do %>
          <%# <span class="icon">
                      <ion-icon name="time-outline"></ion-icon>
                    </span>
                    <span class="title">My meetings</span> %>
          <%# end %>
          <%# </li> %>
          <li class="list" data-sidebar-target="list">
            <b></b>
            <b></b>
            <%= link_to "/users/edit" do %>
              <span class="icon">
                <ion-icon name="settings-outline"></ion-icon>
              </span>
              <span class="title">Setting</span>
            <% end %>
          </li>
          <li class="list" data-sidebar-target="list">
            <b></b>
            <b></b>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="icon">
                <ion-icon name="log-out-outline"></ion-icon>
              </span>
              <span class="title">Log out</span>
            <% end %>
          </li>
        </ul>
      </div>
      <div class='calendar-border'>
        <div class="event-create-container">
          <div class="new-events">
            <H1>Create new meeting:</H1>
            <div class="event-container" data-controller="date">
              <%= simple_form_for([current_user, @event]) do |f| %>
                <div class=new-event-form>
                  <%= f.input :name, label: "Title"%>
                  <%= f.input :description %>
                  <%= f.input :duration, label: "Duration in min"%>
                  <%= f.input :start_time, as: :string, label: "Start", input_html: { id: "start_date", data: { 'date-target' => 'start' } } %>
                  <%= f.input :end_time, as: :string, label: "End", input_html: { id: "end_date", data: { 'date-target' => 'end' }} %>
                  <%= f.input :users, label: "Invitees", collection: @employees, label_method: :first_name, :as => :check_boxes, include_hidden: false %>
                  <%= f.submit "Create meeting", class: 'create-meeting-btn' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/events/show.html.erb
<div class="background">
  <div class="dashboard-container">
    <div class="navigation" data-controller="sidebar" data-action="click->sidebar#active">
      <div class="avatar-picture">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face %>
        <% else %>
          <%= image_tag "avatar_default.png" %>
        <% end %>
      </div>
      <div class="text">
        <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
        <p>My team: <%= link_to current_user.company, events_path, class:"team" %></p>
      </div>
      <ul>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to "/dashboard" do %>
            <span class="icon">
              <ion-icon name="home-outline"></ion-icon>
            </span>
            <span class="title">Calendar</span>
          <% end %>
        </li>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to "/users/edit" do %>
            <span class="icon">
              <ion-icon name="settings-outline"></ion-icon>
            </span>
            <span class="title">Setting</span>
          <% end %>
        </li>
        <li class="list" data-sidebar-target="list">
          <b></b>
          <b></b>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="icon">
              <ion-icon name="log-out-outline"></ion-icon>
            </span>
            <span class="title">Log out</span>
          <% end %>
        </li>
      </ul>
    </div>
    <div class='calendar-border'>
      <div class="card-show">
          <div class="title">
            <H1><%= @event.name %></H1>
          </div>
          <div class="date">
            <span class="icon">
              <ion-icon name="time-outline"></ion-icon>
            </span>
            <p> <%= @event.start_time.strftime("%B %d, %Y")%> </p>
          </div>
          <div class="time">
            <H2> <%= @event.start_time.strftime("%H:%M")%>
              - <%= @event.end_time.strftime("%H:%M") %> </H2>
          </div>
          <div class="description">
            <span class="icon">
              <ion-icon name="list-outline"></ion-icon>
            </span>
            <p>
              <% if !@event.description? %>
                Add description
              <% else %>
              <%= @event.description %>
              <% end %>
            </p>
          </div>
          <div class="attendees">
            <p>Attendees:</p>
            <ul>
              <% @event.user_events.each do |user| %>
                <li><%= user.user.first_name %></li>
              <% end %>
            </ul>
          </div>
          <div class="organiser">
            <p>Organised by:
            <%= @event.user.first_name %></p>
          </div>
          <ul id="links">
            <li>
              <div class="link-icon">
                <%= link_to edit_user_event_path(current_user, @event) do %>
                    <span class="icon">
                      <ion-icon name="create-outline"></ion-icon>
                    </span>
                <% end %>
              </div>
              <div class="link-name">
                <span class="link"> <%= link_to 'Edit', edit_user_event_path(current_user, @event)%> </span>
              </div>
            </li>
            <li>
              <div class="link-icon">
                <%= link_to event_slots_path(@event) do %>
                  <span class="icon">
                    <ion-icon name="code-working-outline"></ion-icon>
                  </span>
                <% end %>
              </div>
              <div class="link-name">
                <span class="link"><%= link_to "Find a slot", event_slots_path(@event) %></span>
              </div>
            </li>
            <li>
              <div class="link-icon">
                <%= link_to event_path(@event),
                              method: :delete,
                              data: { confirm: "Are you sure?" } do %>
                  <span class="icon">
                    <ion-icon name="trash-outline"></ion-icon>
                  </span>
                <% end %>
              </div>
              <div>
                <span class="link">
                  <%= link_to "Delete", event_path(@event),
                              method: :delete,
                              data: { confirm: "Are you sure?" } %>
                </span>
              </div>
            </li>
        </ul>
      </div>
    </div>
  </div>
</div>